In [1]:
import tensorflow as tf
import timeit
from datetime import datetime

In [2]:
def regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b 
    return x

In [3]:
function_that_uses_a_graph = tf.function(regular_function)

In [4]:
x1 = tf.constant([[1, 2, 3]], dtype=tf.float32)
y1 = tf.constant([[2], [3]], dtype=tf.float32)
b1 = tf.constant(4.0)

In [5]:
original_value = regular_function(x1, y1, b1).numpy()
tf_function_value = function_that_uses_a_graph(x1, y1, b1).numpy()
assert(original_value == tf_function_value)

InvalidArgumentError: Matrix size-incompatible: In[0]: [1,3], In[1]: [2,1] [Op:MatMul]

In [6]:
@tf.function
def outer_function(x):
    y = tf.constant([[2], [3]], dtype=tf.float32)
    b = tf.constant(4.0)
    return regular_function(x, y, b)

In [7]:
outer_function(tf.constant([[1.0, 2.0]])).numpy()

array([[12.]], dtype=float32)

In [8]:
@tf.function
def get_MSE(y_true, y_pred):
    print("Calculating MSE!")
    sq_diff = tf.pow(y_true - y_pred, 2)
    return tf.reduce_mean(sq_diff)

In [9]:
y_true = tf.random.uniform([5], maxval=10, dtype=tf.int32)
y_pred = tf.random.uniform([5], maxval=10, dtype=tf.int32)
print(y_true.numpy())
print(y_pred.numpy())

[7 5 2 3 6]
[5 5 9 6 4]


In [10]:
get_MSE(y_true, y_pred).numpy()
get_MSE(y_true, y_pred).numpy()
get_MSE(y_true, y_pred).numpy()

Calculating MSE!


13

In [11]:
tf.config.run_functions_eagerly(True)

In [12]:
@tf.function
def get_MSE2(y_true, y_pred):
    print("Calculating MSE!")
    sq_diff = tf.pow(y_true - y_pred, 2)
    return tf.reduce_mean(sq_diff)

In [13]:
get_MSE2(y_true, y_pred).numpy()
get_MSE2(y_true, y_pred).numpy()
get_MSE2(y_true, y_pred).numpy()

Calculating MSE!
Calculating MSE!
Calculating MSE!


<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [18]:
tf.config.run_functions_eagerly(False)

In [19]:
tf.random.uniform(shape=[10], maxval=10, dtype=tf.int32).numpy()

array([3, 9, 2, 4, 5, 4, 2, 9, 3, 5], dtype=int32)

In [9]:
x = tf.random.uniform(shape=[15, 15], minval=-1, maxval=2, dtype=tf.int32)
x.numpy()

array([[ 1, -1,  0,  0, -1, -1, -1,  1, -1, -1,  0, -1,  1,  0,  1],
       [-1,  0,  0, -1,  1,  0, -1, -1,  0,  0, -1, -1,  1,  0, -1],
       [-1,  0,  0, -1, -1,  0,  0,  0,  0, -1,  1,  0,  1, -1,  1],
       [ 1,  1, -1, -1,  1, -1, -1, -1,  0,  0, -1,  1,  1,  1,  1],
       [ 0,  1,  0, -1,  1,  1,  0,  0, -1,  1,  0, -1,  1, -1,  1],
       [ 0,  1, -1,  1, -1,  1, -1,  0, -1,  1,  0,  1,  0, -1,  1],
       [ 0,  0, -1,  0,  1,  1,  0,  1,  0,  1,  1,  0,  0, -1,  0],
       [ 1,  1,  0, -1,  1, -1,  1, -1,  0,  0,  1, -1, -1,  1, -1],
       [ 0,  1,  0, -1, -1,  0,  0, -1,  0, -1,  0,  1, -1, -1,  0],
       [-1, -1, -1, -1,  0,  1,  0,  1, -1, -1,  0, -1,  1,  0,  0],
       [-1, -1,  0, -1,  0,  1,  0,  1, -1,  0, -1,  0,  1,  0,  1],
       [ 0,  0,  1,  0,  0, -1, -1, -1,  0, -1,  1,  0, -1, -1,  1],
       [ 0,  0, -1,  0, -1,  0, -1,  0,  0,  0,  0, -1, -1,  1,  1],
       [ 1, -1,  0,  1,  0,  0, -1, -1,  1, -1,  1,  0, -1,  0,  0],
       [-1,  0, -1,  1,  0,  1,  1

In [10]:
def powerxy(x, y):
    result = tf.eye(15, dtype=tf.dtypes.int32)
    for _ in range(y):
        result = tf.matmul(x, result)
        return result

powerxy_as_graph = tf.function(powerxy)

In [11]:
print("Eager execution: ", timeit.timeit(lambda: powerxy(x, 10000), number=10000))
print("Graph execution: ", timeit.timeit(lambda: powerxy_as_graph(x, 10000), number=10000))

Eager execution:  0.8286885669804178
Graph execution:  1.0953144509985577
