In [1]:
import tensorflow as tf
import numpy as np

In [9]:
a = tf.constant([[5, 5], [10, 11]], dtype=tf.float16)
tf.nn.softmax(a)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[0.5  , 0.5  ],
       [0.269, 0.731]], dtype=float16)>

In [10]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

In [21]:
-tf.math.log(1.0).numpy()

-0.0

In [26]:
rank_3_tensor[:, 1, 4].numpy()

array([ 9, 19, 29], dtype=int32)

In [40]:
x = tf.constant([1, 2, 3])
y = tf.range(1, 5)
print(x.numpy(),' ',y.numpy())

[1 2 3]   [1 2 3 4]


In [45]:
x_rs = tf.reshape(x, [3, 1])
tf.multiply(x_rs, y).numpy()

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]], dtype=int32)

In [49]:
xy = tf.math.multiply(x_rs, y).numpy()

In [51]:
xz = xy + tf.ones([xy.shape[0], xy.shape[1]])
xz

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 2.,  3.,  4.,  5.],
       [ 3.,  5.,  7.,  9.],
       [ 4.,  7., 10., 13.]], dtype=float32)>

In [53]:
tf.math.multiply(xy, xz).numpy()

array([[  2.,   6.,  12.,  20.],
       [  6.,  20.,  42.,  72.],
       [ 12.,  42.,  90., 156.]], dtype=float32)